### PR TITLE
Sync with upstream: acme-client 2.0.13

### PR DESCRIPTION
**Pull request by jage**
### WHY are these changes introduced?

We need Ruby 3.0 and Faraday 0.17.x compatibility.

### WHAT is this pull request doing?

Syncing with upstream repository, keeping our patch f951848f69a074d0c25d0f35320333d74c8c325c

### HOW can this pull request be tested?

I think specs will cover the gems code, our patch is untested but should be unaffected.

### CODE REVIEW

**Comment by jage** [comment]
Also want to double check we still need f951848f69a074d0c25d0f35320333d74c8c325c @oskgu360? :)

**Comment by dentarg** [comment]
This is great @jage but I want this fork to be a fork of https://github.com/unixcharles/acme-client and not https://github.com/oskgu360/acme-client (if we still need to use a fork)

**Comment by dentarg** [comment]
That has been on my private to do list for quite some time... :)

**Comment by jage** [comment]
Yeah that would be nice, even better if we push this upstream.
But I need this to upgrade to Ruby 3.2.1. :)

**Comment by oskgu360** [comment]
Ah, missed this. I'll try to see if its still needed asap, just gotta read up on the details again hehe

**Review by oskgu360 — APPROVED** [review]
Tried generating a cert without our custom changes, and we do then get the LE default chain which we do not want. So to keep compatibility with older openssl clients (Which I assume we have a few of), we need to keep this custom changes in the fork.

For context: 
https://community.letsencrypt.org/t/long-default-and-short-alternate-certificate-chains-explained/162526

Don't see why this PR would change our behaviour though, so LGTM :)

**Comment by oskgu360** [comment]
The cross-signing of `ISRG Root X1` by `DST Root CA X3` expires on
`Not After : Sep 30 18:14:03 2024 GMT`, my guess is that after this, LE will make the chain we seek default 🤞

**Comment by dentarg** [comment]
Let's work in the direct fork? https://github.com/84codes/acme-client-2

**Pull request closed without merging**
